import SwiftUI

struct SettingsView: View {
    @Environment(\.dismiss) private var dismiss
    @State private var vm = ProfileViewModel()
    private let auth = AuthViewModel.shared

    // MARK: - Trading Settings
    @State private var soundEnabled: Bool = true
    @State private var requireSigmaApproval: Bool = true
    @State private var autoTradingEnabled: Bool = false

    // MARK: - Notification Settings (local)
    @State private var pushNotifications: Bool = true
    @State private var tradeAlerts: Bool = true
    @State private var agentActivityAlerts: Bool = false

    // MARK: - Display Settings (local)
    @State private var compactTradeCards: Bool = false

    // MARK: - State
    @State private var showClearCacheConfirm: Bool = false
    @State private var cacheCleared: Bool = false

    var body: some View {
        NavigationStack {
            ZStack {
                Color.appBackground.ignoresSafeArea()

                ScrollView {
                    VStack(spacing: 20) {
                        // MARK: - Trading Section
                        settingsSection(title: "Trading", icon: "chart.line.uptrend.xyaxis") {
                            VStack(spacing: 14) {
                                Toggle("Sound Effects", isOn: $soundEnabled)
                                    .tint(Color.accentCyan)
                                    .foregroundStyle(.white)

                                Text("Play sound effects for trade executions and alerts.")
                                    .font(.caption)
                                    .foregroundStyle(Color.textMuted)
                                    .frame(maxWidth: .infinity, alignment: .leading)

                                Divider().background(Color.appBorder.opacity(0.3))

                                Toggle("Require Sigma Approval", isOn: $requireSigmaApproval)
                                    .tint(Color.accentCyan)
                                    .foregroundStyle(.white)

                                Text("When enabled, trades generated by Prime will require your manual approval before execution.")
                                    .font(.caption)
                                    .foregroundStyle(Color.textMuted)
                                    .frame(maxWidth: .infinity, alignment: .leading)

                                Divider().background(Color.appBorder.opacity(0.3))

                                Toggle("Auto-Trading", isOn: $autoTradingEnabled)
                                    .tint(Color.accentCyan)
                                    .foregroundStyle(.white)

                                Text("Allow the system to automatically execute approved trade signals without manual confirmation.")
                                    .font(.caption)
                                    .foregroundStyle(Color.textMuted)
                                    .frame(maxWidth: .infinity, alignment: .leading)
                            }
                        }

                        // MARK: - Notifications Section
                        settingsSection(title: "Notifications", icon: "bell.badge") {
                            VStack(spacing: 14) {
                                Toggle("Push Notifications", isOn: $pushNotifications)
                                    .tint(Color.accentCyan)
                                    .foregroundStyle(.white)

                                Divider().background(Color.appBorder.opacity(0.3))

                                Toggle("Trade Alerts", isOn: $tradeAlerts)
                                    .tint(Color.accentCyan)
                                    .foregroundStyle(.white)

                                Text("Get notified when trades are opened, closed, or hit stop-loss/target.")
                                    .font(.caption)
                                    .foregroundStyle(Color.textMuted)
                                    .frame(maxWidth: .infinity, alignment: .leading)

                                Divider().background(Color.appBorder.opacity(0.3))

                                Toggle("Agent Activity Alerts", isOn: $agentActivityAlerts)
                                    .tint(Color.accentCyan)
                                    .foregroundStyle(.white)

                                Text("Get notified when AI agents detect important market signals or patterns.")
                                    .font(.caption)
                                    .foregroundStyle(Color.textMuted)
                                    .frame(maxWidth: .infinity, alignment: .leading)
                            }
                        }

                        // MARK: - Display Section
                        settingsSection(title: "Display", icon: "paintbrush") {
                            VStack(spacing: 14) {
                                HStack {
                                    Text("Always Dark Mode")
                                        .foregroundStyle(.white)
                                    Spacer()
                                    PillBadgeView(text: "ON", color: Color.accentCyan)
                                }

                                Text("AalsiTrader is designed for dark mode only for optimal chart readability.")
                                    .font(.caption)
                                    .foregroundStyle(Color.textMuted)
                                    .frame(maxWidth: .infinity, alignment: .leading)

                                Divider().background(Color.appBorder.opacity(0.3))

                                Toggle("Compact Trade Cards", isOn: $compactTradeCards)
                                    .tint(Color.accentCyan)
                                    .foregroundStyle(.white)

                                Text("Show trade cards in a compact single-line layout to see more trades at once.")
                                    .font(.caption)
                                    .foregroundStyle(Color.textMuted)
                                    .frame(maxWidth: .infinity, alignment: .leading)
                            }
                        }

                        // MARK: - Data Section
                        settingsSection(title: "Data", icon: "externaldrive") {
                            VStack(spacing: 14) {
                                // Clear cache
                                HStack {
                                    VStack(alignment: .leading, spacing: 2) {
                                        Text("Clear Cache")
                                            .foregroundStyle(.white)
                                        Text("Remove locally cached data and images")
                                            .font(.caption)
                                            .foregroundStyle(Color.textMuted)
                                    }
                                    Spacer()
                                    Button {
                                        showClearCacheConfirm = true
                                    } label: {
                                        Text(cacheCleared ? "Cleared" : "Clear")
                                            .font(.caption.bold())
                                            .foregroundStyle(cacheCleared ? Color.profitGreen : Color.statusWarning)
                                            .padding(.horizontal, 12)
                                            .padding(.vertical, 6)
                                            .background(
                                                (cacheCleared ? Color.profitGreen : Color.statusWarning).opacity(0.15)
                                            )
                                            .clipShape(Capsule())
                                    }
                                    .disabled(cacheCleared)
                                }

                                Divider().background(Color.appBorder.opacity(0.3))

                                // Export trade history
                                HStack {
                                    VStack(alignment: .leading, spacing: 2) {
                                        Text("Export Trade History")
                                            .foregroundStyle(.white)
                                        Text("Download your trades as a CSV file")
                                            .font(.caption)
                                            .foregroundStyle(Color.textMuted)
                                    }
                                    Spacer()
                                    Button {
                                        // Placeholder - export functionality
                                        HapticService.impact(.light)
                                    } label: {
                                        Text("Export")
                                            .font(.caption.bold())
                                            .foregroundStyle(Color.accentCyan)
                                            .padding(.horizontal, 12)
                                            .padding(.vertical, 6)
                                            .background(Color.accentCyan.opacity(0.15))
                                            .clipShape(Capsule())
                                    }
                                }
                            }
                        }

                        // MARK: - Save Button
                        Button {
                            Task {
                                await vm.saveSettings(
                                    soundEnabled: soundEnabled,
                                    requireSigmaApproval: requireSigmaApproval
                                )
                            }
                        } label: {
                            if vm.isSaving {
                                ProgressView()
                                    .tint(.white)
                                    .frame(maxWidth: .infinity)
                                    .padding(.vertical, 14)
                            } else {
                                Text("Save Settings")
                                    .font(.headline)
                                    .foregroundStyle(.black)
                                    .frame(maxWidth: .infinity)
                                    .padding(.vertical, 14)
                            }
                        }
                        .background(Color.accentCyan)
                        .clipShape(RoundedRectangle(cornerRadius: 12))
                        .disabled(vm.isSaving)
                        .opacity(vm.isSaving ? 0.7 : 1)

                        if let success = vm.successMessage {
                            Text(success)
                                .font(.caption).foregroundStyle(Color.profitGreen)
                        }

                        // App info footer
                        VStack(spacing: 4) {
                            Text("AalsiTrader iOS")
                                .font(.caption)
                                .foregroundStyle(Color.textSecondary)
                            Text("v1.0.0 (Build 1)")
                                .font(.caption2)
                                .foregroundStyle(Color.textMuted)
                        }
                        .padding(.top, 8)
                        .padding(.bottom, 24)
                    }
                    .padding()
                }
            }
            .navigationTitle("Settings")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .topBarTrailing) {
                    Button("Done") { dismiss() }
                        .foregroundStyle(Color.accentCyan)
                }
            }
            .onAppear {
                if let settings = auth.user?.settings {
                    soundEnabled = settings.soundEnabled
                    requireSigmaApproval = settings.requireSigmaApproval
                }
            }
            .alert("Clear Cache?", isPresented: $showClearCacheConfirm) {
                Button("Cancel", role: .cancel) {}
                Button("Clear", role: .destructive) {
                    URLCache.shared.removeAllCachedResponses()
                    cacheCleared = true
                    HapticService.success()
                }
            } message: {
                Text("This will remove all locally cached data. Your account data will not be affected.")
            }
        }
    }

    // MARK: - Section Builder

    private func settingsSection(
        title: String,
        icon: String,
        @ViewBuilder content: () -> some View
    ) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(spacing: 8) {
                Image(systemName: icon)
                    .font(.subheadline)
                    .foregroundStyle(Color.accentCyan)
                Text(title)
                    .font(.headline)
                    .foregroundStyle(.white)
            }
            .padding(.horizontal, 4)

            VStack(alignment: .leading, spacing: 0) {
                content()
            }
            .padding(14)
            .cardStyle()
        }
    }
}
